filetype plugin indent on

set runtimepath=~/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/.vim/after
set grepprg=grep\ -nH\ $*
set whichwrap+=<,>,h,l
set incsearch
set lazyredraw
set magic
set showmatch
set mat=2
set encoding=utf8
set ai
set si
set wrap
set smartcase

if has("gui_running")
    set guioptions-=T
    set guioptions-=e
    set t_Co=256
    set guitablabel=%M\ %t
endif

if has('filetype')
    filetype indent plugin on
endif

if has('syntax')
	syntax on
endif

if has('mouse')
	set mouse=a
endif

set nocompatible
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set laststatus=2
set confirm
set cmdheight=2
set number
set shiftwidth=4
set softtabstop=4
set expandtab
set background=dark

map Y y$
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

set path+=**
command! MakeTags !ctags -R .

let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
let g:tex_flavor = "latex"
let g:vimwiki_menu = "Vimwiki"
let g:vimwiki_list = [{'path': '~/Documents/Escola/vimwiki/',
                     \ 'path_html': '~/Documents/Escola/html/vimwiki_html',
                     \ 'auto_export': 1}]

nnoremap ,html :-1read $HOME/.vim/.skeleton.html<CR>5jf>a
nnoremap ,c :-1read $HOME/.vim/.skeleton.c<CR>3jA
nnoremap ,+ :-1read $HOME/.vim/.skeleton.cpp<CR>4jA

au CursorHoldI * stopinsert
au InsertEnter * silent! let updaterestore=&updatetime | set updatetime=60000 | execute "!setxkbmap -option caps:swapescape" | redraw!
au InsertLeave * silent! let &updatetime=updaterestore | execute "!setxkbmap -option" | redraw!

color torte
