#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu, emacsclient
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Simon Ingelsson
#               HostGrady
# Usage:
# to use other editor than emacsclient set DMEDITOR accordingly
#   Example: `DMEDITOR="alacritty -e nvim" ./dmconf`

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

config="$HOME/.config/dmscripts/config"
# No issues should arrise since it won't even be sourced if the file doesn't exist
# shellcheck disable=SC1090
[[ -f "$config" ]] && source "$config"

: "${DMEDITOR:=st -e vim}"

if [[ ! "$(declare -p options 2>/dev/null)" == "declare -A"* ]] ; then 
  declare -A options
  options[alacritty]="$HOME/.config/alacritty/alacritty.yml"
  options[bash]="$HOME/.bashrc"
  options[dunst]="$HOME/.config/dunst/dunstrc"
  options[i3]="$HOME/.config/i3/config"
  options[i3status]="$HOME/.config/i3status/config"
  options[neovim]="$HOME/.config/nvim/init.vim"
  options[picom]="$HOME/.config/picom.conf"
  options[polybar]="$HOME/.config/polybar/config"
  options[qtile]="$HOME/.config/qtile/config.py"
  options[qutebrowser]="$HOME/.config/qutebrowser/config.py"
  options[ssh]="$HOME/.ssh/config"
  options[vim]="$HOME/.vim/vimrc"
fi

# Clean options array making sure that the files exist
declare -A options_clean
  for i in "${!options[@]}"; do
    [[ -f ${options["${i}"]} ]] && options_clean["${i}"]=${options["${i}"]}
  done

# Piping the above array (cleaned) into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${!options_clean[@]}" | sort | $DMENU -l 20 -p 'Edit config:')

# What to do when/if we choose a file to edit.
if [ "$choice" ]; then
  cfg=$(printf '%s\n' "${options_clean["${choice}"]}")
  $DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 0
fi
