#!/usr/bin/env bash
#
# Script name: dmscrot
# Description: Choose type of screenshot to take with maim.
# Dependencies: dmenu, maim, tee, xdotool, xclip, xrandr
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Simon Ingelsson
#               Steven Hall


# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

config="${HOME}/.config/dmscripts/config"
# No issues should arrise since it won't even be sourced if the file doesn't exist
# shellcheck disable=SC1090	
[ -f "${config}" ] && source "${config}"

# Defaults (Override in config)
: "${SCROTDIR:=${HOME}/Screenshots}"

# Makes sure the directory exists.
mkdir -p "${SCROTDIR}"

getStamp() {
  date '+%Y%m%d-%H%M%S'
}

_maim_args=""
_file_type=""

# What modes do we have
declare -a modes=(
"Fullscreen"
"Active window"
"Selected region"
)

target=$(printf '%s\n' "${modes[@]}" | $DMENU -l 20 -p 'Take screenshot of:') || exit 1
case "$target" in
  'Fullscreen')
    _file_type="full"
  ;;
  'Active window')
    active_window=$(xdotool getactivewindow)
    _maim_args="-i ${active_window}"
    _file_type="window"
  ;;
  'Selected region')
    _maim_args="-s"
    _file_type="region"
  ;;
  *)
    _maim_args="-g ${_display_mode[${target}]}"
    _file_type="${target}"
  ;;
esac

declare -a destination=( "File" "Clipboard" "Both" )
dest=$(printf '%s\n' "${destination[@]}" | $DMENU -l 20 -p 'Destination:' ) || exit 1
case "$dest" in
  'File')
    # shellcheck disable=SC2086
    sleep .2
    maim ${_maim_args} "${SCROTDIR}/scrot-${_file_type}-$(getStamp).png"
  ;;
  'Clipboard')
    # shellcheck disable=SC2086
    sleep .2
    maim ${_maim_args} | xclip -selection clipboard -t image/png
  ;;
  'Both')
    # shellcheck disable=SC2086
    sleep .2
    maim ${_maim_args} | tee "${SCROTDIR}/scrot-${_file_type}-$(getStamp).png" | xclip -selection clipboard -t image/png
  ;;
  *)
    exit 1
  ;;
esac

exit 0
